### ISSUE TITLE
部署 csi-cephfsplugin.yaml 时出现错误

### ISSUE THREAD

**Issue by gotohx** [Daydreamer-zz/cephfs-csi-deploy#1]
hi，我在执行 **kubectl apply -f csi-cephfsplugin.yaml** 命令后，Rancher 上出现如下警告：

“MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry/ is not a directory” ，

请问可以请教一下解决办法吗？

k8s 版本：1.16.15
ceph版本：15.2.15

**Comment by Daydreamer-zz** [comment]
node节点上建一个这个目录`/var/lib/kubelet/plugins_registry/`，我看了下这个csi-cephfsplugin的DaemonSet会挂载这个hostpath类型的volume

**Comment by gotohx** [comment]
我之后是这样解决的，但在部署 pvc 这个文件时，又出现了下面这个错误：


failed to provision volume with StorageClass  "csi-cephfs-sc": rpc error: code = InvalidArgument desc = failed to get  connection: connecting failed: rados: ret=-22, Invalid argument

**Comment by gotohx** [comment]
> 
> 
> 我之后是这样解决的，但在部署 pvc 这个文件时，又出现了下面这个错误：
> 
> failed to provision volume with StorageClass "csi-cephfs-sc": rpc error: code = InvalidArgument desc = failed to get connection: connecting failed: rados: ret=-22, Invalid argument
![捕获](https://user-images.githubusercontent.com/23432183/142593523-4e246f5d-c621-4157-8d69-a93c543365d0.PNG)

**Comment by Daydreamer-zz** [comment]
看一下csi-cephfsplugin的日志，好像是你的ceph秘钥的问题，确定key填的是正确的吗
好像和这个issue差不多[https://github.com/ceph/ceph-csi/issues/2254#issue-939925640](url)

**Comment by Daydreamer-zz** [comment]
看一下csi-cephfsplugin的日志，好像是你的ceph秘钥的问题，确定key填的是正确的吗
[https://github.com/ceph/ceph-csi/issues/2254](url)

**Comment by Daydreamer-zz** [comment]
看一下csi-cephfsplugin的日志，好像是你的ceph秘钥的问题，确定key填的是正确的吗
看一下这个issue好像差不多[https://github.com/ceph/ceph-csi/issues/2254#issue-939925640](url)

**Comment by gotohx** [comment]
万分感谢，确实是密钥问题，我通过 **ceph auth get-key client.admin** 获得密钥后，还对密钥进行了 base64 加密，secret.yaml 中用的是 stringData，实际不应该加密。

**Comment by gotohx** [comment]
另外一个问题希望可以再请教下，在部署测试 pod 时，出现下面这个错误：
![捕获](https://user-images.githubusercontent.com/23432183/142602406-e19471ed-ce06-4497-9314-fae87825808d.PNG)

“kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name cephfs.csi.ceph.com not found in the list of registered CSI drivers”

这是因为 plugins_registry 这个目录是手动创建的吗

**Comment by Daydreamer-zz** [comment]
csidriver.yaml开头的注释， k8s集群版本小于1.18需要把apiversion改成v1beta1，你的1.16是需要改的

**Comment by gotohx** [comment]
这个我之前已经改了

**Comment by Daydreamer-zz** [comment]
抱歉我这里没有1.16的集群测试，我感觉这个测试pod调度节点可能没有csi-cephfsplugin这个pod，可能是有污点csi-cephfsplugin没有调度过去，我查了大部分类似的问题基本都是这个问题，或许在csi-cephfsplugin添加容忍解决

**Comment by gotohx** [comment]
我看了下 csi-cephfsplugin 这个 pod 在每个节点都成功部署了，不像是这个原因，我再研究下，有结果后再来反馈。非常感谢你的帮助。

**Comment by gotohx** [comment]
问题已解决：

需要把 csi-cephfsplugin.yaml 中的  /var/lib/kubelet 这个路径（共有七处）全部替换成实际服务器上 kubelet 路径，在我这是 /data/kubelet 这个路径；另外，在 /data/kubelet 也发现了plugins_registry 这个文件夹，不再需要手动创建。

再次感谢你的帮助！

**Comment by Daydreamer-zz** [comment]
哦，这样啊，/var/lib/kubelet这个路径是kubelet默认的路径，rancher没用过，rancher安装的k8s默认的kubelet路径是/data/kubelet吗，还是你手动修改过kubelet的root-dir

**Comment by gotohx** [comment]
rancher 默认路径应该不是 /data/kubelet，应该是同事手动指定的。但服务器上也有 /var/lib/kubelet 这个路径，所以一开始没往这块想。

**Comment by Daydreamer-zz** [comment]
好的，感谢分享！
